import React from 'react'
import { Link } from 'react-router-dom'

/**
 * Terms and privacy, served from the app rather than a CMS so they ship and
 * version with the thing they describe.
 *
 * Written to place the risks where the decisions are made: the customer says
 * what to collect and from where, so the customer carries the warranty that
 * they may. Two clauses do most of the work — the accuracy disclaimer, because
 * the output is generated by a model reading pages it does not control, and
 * the restricted-platform clause, which ties to the acknowledgement recorded
 * in Settings.
 *
 * Not legal advice, and not a substitute for a lawyer reading it before this
 * is used with paying customers.
 */
function Shell({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) {
  return (
    <div className="landing">
      <header>
        <Link to="/" className="brand" style={{ color: 'var(--text)', padding: 0 }}>
          <span className="grad-text" aria-hidden>
            ✦
          </span>
          <span className="word">huntwell</span>
        </Link>
        <div className="row">
          <Link to="/terms" className="btn">
            Terms
          </Link>
          <Link to="/privacy" className="btn">
            Privacy
          </Link>
        </div>
      </header>
      <div className="legal doc">
        <h1>{title}</h1>
        <p className="muted">Last updated {updated}</p>
        {children}
        <p className="muted" style={{ marginTop: '2.5rem' }}>
          Questions about this page: <a href="mailto:legal@huntwell.app">legal@huntwell.app</a>
        </p>
      </div>
    </div>
  )
}

export function Terms() {
  return (
    <Shell title="Terms of Service" updated="4 September 2026">
      <p>
        These terms govern your use of Huntwell (the “Service”), operated by Yak Systems, Inc. (“we”, “us”). By creating an account
        or using the Service you agree to them. If you are agreeing on behalf of an organisation, you confirm you may bind
        it.
      </p>

      <h2>1. What the Service does</h2>
      <p>
        Huntwell runs automated searches of publicly accessible web pages <b>at your direction</b>, using instructions you
        provide, and stores the results in your workspace. You decide what is collected, from where, and how often. We
        provide the machinery; we do not choose your targets and we do not review what you ask for.
      </p>

      <h2>2. Your responsibilities</h2>
      <p>You are responsible for what you instruct the Service to collect and for what you do with the results. You warrant that:</p>
      <ul>
        <li>you have the right to collect, store and use the data your plans gather, and a lawful basis for any personal data;</li>
        <li>your use complies with all applicable laws, including data protection, anti-spam and consumer protection law;</li>
        <li>you will honour the terms of the sites you direct the Service to read, and any refusal signals they publish;</li>
        <li>you will not use the Service to collect data about children, or special-category data (health, biometrics, religion, sexual orientation, political opinion, trade union membership) or equivalents;</li>
        <li>you will not use the Service to stalk, harass, discriminate, defraud, or build a profile of a person for those purposes;</li>
        <li>you will not resell raw output as a data product without independently verifying it and holding your own lawful basis.</li>
      </ul>

      <h2>3. Restricted platforms</h2>
      <p>
        The Service does not collect from LinkedIn, Facebook, Instagram, X or Threads unless you explicitly record, in
        Settings, that you hold the right to do so. That record is dated and kept. If you enable it, you accept sole
        responsibility for that collection, including any claim by the platform, and you may withdraw it at any time.
      </p>

      <h2>4. Accuracy — read this one</h2>
      <p>
        Results are produced by an automated agent reading third-party pages. They may be incomplete, out of date, mistaken
        or fabricated, and pages may themselves be wrong or deliberately misleading. <b>The Service is provided “as is”, with
        no warranty of accuracy, completeness or fitness for a particular purpose.</b> You must verify anything you rely on,
        and you must not present output as verified fact without checking it. Do not use the Service as the sole basis for
        any decision with a legal or material effect on a person.
      </p>

      <h2>5. Data protection</h2>
      <p>
        For personal data your plans collect, you are the controller and we are your processor: we process it on your
        instructions, to provide the Service. You are responsible for the notices, lawful basis and responses to data
        subject requests that the law requires of a controller. We will assist where we reasonably can, and we will delete
        a workspace’s data on request or on account closure. Our own handling of your account data is described in the{' '}
        <Link to="/privacy">Privacy Policy</Link>.
      </p>

      <h2>6. Acceptable use and suspension</h2>
      <p>
        We may suspend or terminate an account that breaches these terms, that we reasonably believe exposes us to legal
        claims, or that is the subject of a credible complaint from a site owner or a person whose data was collected. Where
        practical we will tell you first.
      </p>

      <h2>7. Fees</h2>
      <p>
        Executions consume metered resources and are billed as described in the app. Charges are incurred when a plan runs,
        including runs that return nothing. Unpaid accounts may be suspended.
      </p>

      <h2>8. Indemnity</h2>
      <p>
        You will indemnify and hold us harmless against claims, damages, fines and reasonable legal costs arising from your
        use of the Service, your instructions, the data you collect, or your breach of these terms — including claims by a
        website operator, a platform, or a person whose data your plans gathered.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the fullest extent the law allows, we are not liable for indirect, incidental, special or consequential loss, nor
        for lost profits, revenue, goodwill or data. Our total liability for any claim is limited to the fees you paid in the
        three months before the event giving rise to it. Nothing here excludes liability that cannot lawfully be excluded.
      </p>

      <h2>10. Changes and governing law</h2>
      <p>
        We may change these terms; material changes will be notified in the app or by email, and continued use after that is
        acceptance. These terms are governed by the laws of the State of Nevada, USA, and the courts there have exclusive
        jurisdiction, without regard to conflict-of-law rules.
      </p>
    </Shell>
  )
}

export function Privacy() {
  return (
    <Shell title="Privacy Policy" updated="4 September 2026">
      <p>
        This policy covers data we hold about <b>you, our customer</b>. Data your search plans collect about other people is
        yours: you are its controller and we process it on your behalf, as set out in the <Link to="/terms">Terms</Link>.
      </p>

      <h2>What we hold about you</h2>
      <ul>
        <li><b>Account:</b> your name, email address, password hash, timezone and workspace membership.</li>
        <li><b>Billing:</b> a customer reference and card details held by our payment processor. We never see or store your full card number.</li>
        <li><b>Usage:</b> executions, token consumption and cost, so we can meter and bill.</li>
        <li><b>Logs:</b> what your executions did, kept so you can audit them and so we can debug failures.</li>
      </ul>

      <h2>What your plans collect</h2>
      <p>
        Whatever your plans are instructed to collect, stored in your workspace, with the source URL for each row. We do not
        sell it, mine it, or use it to train models. We access it only to operate the Service or where you ask us to help.
      </p>

      <h2>Processors we use</h2>
      <p>
        Model inference, remote browsers, transactional email, payments and hosting are provided by third parties acting on
        our instructions. A current list is available on request. Pages your plans read are sent to a model provider in order
        to extract results from them.
      </p>

      <h2>Retention and your rights</h2>
      <p>
        Account and usage data is kept while your account is open and for as long afterwards as tax and accounting rules
        require. Collected data is deleted when you delete the plan or close the account. Depending on where you live you may
        have rights to access, correct, export or delete your personal data, and to object to processing — write to us and we
        will act within the period the law allows.
      </p>

      <h2>Security</h2>
      <p>
        Passwords are hashed. Connected browser sessions are held by our remote-browser provider so that credentials you type
        on a site never reach us — we never receive your password for another service. Access to production data is limited
        to those who need it.
      </p>
    </Shell>
  )
}
