-- A signed-up user. Everything else in the database hangs off account_id, so a
-- query that forgets to filter by it is a cross-tenant leak: every store
-- function takes the account explicitly and never trusts a bare plan_id.
--
-- No password, hash or authenticator secret lives here, in any environment:
-- identity is an AWS Cognito user pool and the row keys to it by subject.
CREATE TABLE IF NOT EXISTS public.account (
	account_id        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	-- Stored lowercased; the unique constraint is what makes sign-in
	-- case-insensitive without a citext extension.
	email             varchar(320) NOT NULL,
	display_name      varchar(120) NOT NULL DEFAULT '',
	-- The Cognito subject this account is. Keyed on `sub` rather than on the
	-- email address because an address can be changed in the pool and the
	-- subject never is; a row keyed to the address would silently detach the
	-- day somebody edits one. Empty only until a pre-pool row's first sign-in.
	cognito_sub       varchar(64) NOT NULL DEFAULT '',
	-- IANA zone name. Schedules are entered as local wall-clock and this is
	-- what turns them into a UTC next_run_at.
	timezone          varchar(64) NOT NULL DEFAULT 'UTC',
	-- Whether the timezone tracks this person's browser (the default) or was
	-- chosen by hand in Settings. Without it the browser sync would silently
	-- overwrite a deliberate choice on the next page load.
	timezone_auto     boolean NOT NULL DEFAULT true,
	-- 'light' | 'dark' | 'system'. Also kept in the browser; this copy is what
	-- follows the user to another machine.
	theme             varchar(16) NOT NULL DEFAULT 'system',
	created_at        timestamptz NOT NULL DEFAULT now(),
	last_login_at     timestamptz,
	-- When the account finished first-run setup (name + timezone). NULL means
	-- the setup dialog has not been completed, which is what the UI shows it
	-- on: the row exists from signup, so "have they been here before" cannot
	-- be inferred from last_login_at (login writes it before the first screen).
	onboarded_at      timestamptz,
	-- The workspace this person is currently working in, when it is not their
	-- own. Every data query filters by the tenant account.account_id; this is
	-- what decides which one that is (see Account::tenant / membership.sql).
	-- NULL — the normal case — means their own workspace.
	active_workspace_id bigint,
	-- What the workspace this account owns is called, when it is more than one
	-- person's own. Empty — the normal case for a solo account — reads as
	-- "<name>'s workspace" wherever it is shown, so nobody has to name anything
	-- until there is somebody else in it.
	workspace_name    varchar(120) NOT NULL DEFAULT '',
	-- Which plan kinds this account may create, comma-separated. Empty means
	-- "use the installation default" (control_setting 'kinds_default'), so
	-- turning a feature on for everyone does not mean touching every row.
	enabled_kinds     text NOT NULL DEFAULT '',
	-- When this account claimed the right to collect from the restricted
	-- platforms (see guard::RESTRICTED_HOSTS). NULL means runs refuse those
	-- hosts. A timestamp rather than a flag because what matters in a dispute
	-- is when it was accepted — and by whom, and what the wording was: a date
	-- alone proves a box was ticked.
	platform_ack_at   timestamptz,
	platform_ack_by   bigint,
	platform_ack_text text NOT NULL DEFAULT '',
	-- Whether this workspace may connect an authenticated session — logging in
	-- once so runs collect the way a signed-in person sees a site. Off by
	-- default, deliberately: the failure mode of shipping it on is a
	-- workspace's real credentials in a remote browser doing something nobody
	-- checked. An operator turns it on per workspace in the admin console.
	connected_logins  boolean NOT NULL DEFAULT false,
	-- Proof the address is theirs. NULL from sign-up until the emailed code is
	-- entered; until then nothing but sign-out and resend works, and an
	-- invitation cannot be accepted — a squatter registering someone's address
	-- proves nothing.
	email_verified_at timestamptz,
	-- SHA-256 of the six-digit code that was emailed, when it was sent (good
	-- for 15 minutes), and how many wrong guesses it has taken (five ends it:
	-- a new code has to be asked for, which keeps a million-way guess out).
	verify_token_hash char(64) NOT NULL DEFAULT '',
	verify_sent_at    timestamptz,
	verify_attempts   integer NOT NULL DEFAULT 0,
	-- Forgot-password: the same three, for the reset code.
	reset_token_hash  char(64) NOT NULL DEFAULT '',
	reset_sent_at     timestamptz,
	reset_attempts    integer NOT NULL DEFAULT 0,
	-- Two-factor (TOTP). The secret lives in the pool; this is only a mirror
	-- of whether it is on, for the UI.
	mfa_enabled_at    timestamptz,
	PRIMARY KEY (account_id),
	UNIQUE (email)
);
CREATE UNIQUE INDEX IF NOT EXISTS account_cognito_sub_idx
    ON public.account (cognito_sub) WHERE cognito_sub <> '';
