-- A signed-up user. Everything else in the database hangs off account_id, so a
-- query that forgets to filter by it is a cross-tenant leak: every store
-- function takes the account explicitly and never trusts a bare plan_id.
CREATE TABLE IF NOT EXISTS public.account (
	account_id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	-- Stored lowercased; the unique constraint is what makes sign-in
	-- case-insensitive without a citext extension.
	email        varchar(320) NOT NULL,
	display_name  varchar(120) NOT NULL DEFAULT '',
	-- argon2id PHC string. Never anything reversible.
	password_hash text NOT NULL,
	-- IANA zone name. Schedules are entered as local wall-clock and this is
	-- what turns them into a UTC next_run_at.
	timezone     varchar(64) NOT NULL DEFAULT 'UTC',
	-- 'light' | 'dark' | 'system'. Also kept in the browser; this copy is what
	-- follows the user to another machine.
	theme        varchar(16) NOT NULL DEFAULT 'system',
	created_at    timestamptz NOT NULL DEFAULT now(),
	last_login_at  timestamptz,
	PRIMARY KEY (account_id),
	UNIQUE (email)
);

-- When the account finished first-run setup (name + timezone). NULL means the
-- setup dialog has not been completed, which is what the UI shows it on: the
-- row exists from signup, so "have they been here before" cannot be inferred
-- from last_login_at (login writes it before the first screen renders).
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS onboarded_at timestamptz;

-- The workspace this person is currently working in, when it is not their own.
-- Every data query filters by the tenant account.account_id; this is what
-- decides which one that is (see Account::tenant / membership.sql). NULL — the
-- normal case — means their own workspace.
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS active_workspace_id bigint;

-- What the workspace this account owns is called, when it is more than one
-- person's own. Empty — the normal case for a solo account — reads as
-- "<name>'s workspace" wherever it is shown, so nobody has to name anything
-- until there is somebody else in it.
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS workspace_name varchar(120) NOT NULL DEFAULT '';

-- Whether the timezone tracks this person's browser (the default) or was
-- chosen by hand in Settings. Without it the browser sync would silently
-- overwrite a deliberate choice on the next page load.
ALTER TABLE account ADD COLUMN IF NOT EXISTS timezone_auto boolean NOT NULL DEFAULT true;

-- Which plan kinds this account may create, comma-separated. Empty means "use
-- the installation default" (control_setting 'kinds_default'), so turning a
-- feature on for everyone does not mean touching every row.
ALTER TABLE account ADD COLUMN IF NOT EXISTS enabled_kinds text NOT NULL DEFAULT '';

-- When this account claimed the right to collect from the restricted platforms
-- (see guard::RESTRICTED_HOSTS). NULL means runs refuse those hosts. Stored as
-- a timestamp rather than a flag because what matters in a dispute is when it
-- was accepted, not that it is on.
ALTER TABLE account ADD COLUMN IF NOT EXISTS platform_ack_at timestamptz;

-- Who accepted, and the wording they accepted. A date alone proves a box was
-- ticked; a dispute asks which person ticked it and what it said at the time.
ALTER TABLE account ADD COLUMN IF NOT EXISTS platform_ack_by   bigint;
ALTER TABLE account ADD COLUMN IF NOT EXISTS platform_ack_text text NOT NULL DEFAULT '';

-- Whether this workspace may connect an authenticated session — logging in once
-- so runs collect the way a signed-in person sees a site.
--
-- Off by default and off for every existing row, deliberately: the feature is
-- untested, and the failure mode of shipping it on is not a broken page but a
-- workspace's real credentials in a remote browser doing something nobody
-- checked. An operator turns it on per workspace in the admin console.
--
-- A plain boolean rather than the "empty means installation default" shape
-- enabled_kinds uses: that shape exists to make turning a feature on for
-- everyone cheap, and this is the opposite — nothing gets it until someone
-- decides that workspace should have it.
ALTER TABLE account ADD COLUMN IF NOT EXISTS connected_logins boolean NOT NULL DEFAULT false;

-- The Cognito subject this account is, when identity lives in a user pool
-- (identity.rs: `cognito` provider). Empty on a local-identity install, which
-- is what a dev box runs — the two are never both filled.
--
-- Keyed on `sub` rather than on the email address because an address can be
-- changed in the pool and the subject never is; a row keyed to the address
-- would silently detach the day somebody edits one.
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS cognito_sub varchar(64) NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS account_cognito_sub_idx
    ON public.account (cognito_sub) WHERE cognito_sub <> '';

-- Under Cognito nothing here holds a password, so the column has to stop being
-- a required value. It is not dropped: a local-identity install still uses it,
-- and dropping a NOT NULL column that shipped is not something a migration that
-- has already run everywhere can do.
ALTER TABLE public.account ALTER COLUMN password_hash SET DEFAULT '';

-- Proof the address is theirs. NULL from sign-up until the link in the
-- verification email is followed; until then nothing but sign-out and resend
-- works, and an invitation cannot be accepted — a squatter registering
-- someone's address proves nothing. Rows that predate this column are
-- backfilled as verified: the DEFAULT applies once, on ADD, and is dropped.
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS email_verified_at timestamptz DEFAULT now();
ALTER TABLE public.account ALTER COLUMN email_verified_at DROP DEFAULT;
-- SHA-256 of the six-digit code that was emailed, when it was sent (good for
-- 15 minutes), and how many wrong guesses it has taken (five ends it: a new
-- code has to be asked for, which is what keeps a million-way guess out).
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS verify_token_hash char(64) NOT NULL DEFAULT '';
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS verify_sent_at timestamptz;
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS verify_attempts integer NOT NULL DEFAULT 0;
