-- Operators of the admin control plane. Entirely separate from account (the
-- product's tenants): operators sign in through their own Cognito pool
-- (ADMIN_COGNITO_*), kept apart from the product's so a customer account can
-- never be an operator and the two directories can be locked down
-- differently. The row is keyed to that pool by subject; no password is
-- stored here in any form. Seeded at admin startup from HUNTWELL_ADMIN_EMAIL /
-- HUNTWELL_ADMIN_PASSWORD (the operator is made in the pool, then recorded).
CREATE TABLE IF NOT EXISTS public.admin_user (
	admin_user_id  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	email          varchar(200) NOT NULL,
	cognito_sub    varchar(64) NOT NULL DEFAULT '',
	created_at     timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (admin_user_id),
	UNIQUE (email)
);
CREATE UNIQUE INDEX IF NOT EXISTS admin_user_cognito_sub_idx
    ON public.admin_user (cognito_sub) WHERE cognito_sub <> '';
