-- Operators of the admin control plane. Entirely separate from account
-- (the product's tenants): admin runs on its own server against the core DB
-- and must not depend on the auth service. Seeded at admin startup from
-- HUNTWELL_ADMIN_EMAIL / HUNTWELL_ADMIN_PASSWORD (idempotent upsert, so
-- re-seeding is a password reset).
CREATE TABLE IF NOT EXISTS public.admin_user (
	admin_user_id  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	email        varchar(200) NOT NULL,
	password_hash varchar(200) NOT NULL,
	created_at    timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (admin_user_id),
	UNIQUE (email)
);
