-- Every download-API attempt: time, key (if any matched), address, outcome.
-- Capped per account by the store so a probe cannot grow the table forever.
CREATE TABLE IF NOT EXISTS public.api_audit (
	audit_id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	account_id bigint,
	key_id     bigint,
	at        timestamptz NOT NULL DEFAULT now(),
	ip        varchar(64) NOT NULL DEFAULT '',
	outcome   varchar(32) NOT NULL DEFAULT '',
	path      varchar(200) NOT NULL DEFAULT '',
	PRIMARY KEY (audit_id)
);
CREATE INDEX IF NOT EXISTS api_audit_at_idx ON public.api_audit (audit_id DESC);
