-- Download API credentials. Only the SHA-256 of the token is stored; the token
-- itself is shown once, at creation. No foreign key to account: ownership is
-- enforced in application code, where every store function filters by it.
CREATE TABLE IF NOT EXISTS public.api_key (
	key_id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	account_id  bigint NOT NULL,
	-- NULL = every plan the account owns.
	plan_id     bigint,
	token_hash  char(64) NOT NULL,
	token_hint  varchar(16) NOT NULL DEFAULT '',
	label      varchar(120) NOT NULL DEFAULT '',
	-- CSV of IPs/CIDRs; '' = anywhere.
	allow_cidr  text NOT NULL DEFAULT '',
	expires_at  timestamptz,
	created_at  timestamptz NOT NULL DEFAULT now(),
	last_used_at timestamptz,
	last_used_ip varchar(64) NOT NULL DEFAULT '',
	uses       integer NOT NULL DEFAULT 0,
	revoked    boolean NOT NULL DEFAULT false,
	PRIMARY KEY (key_id),
	UNIQUE (token_hash),
	FOREIGN KEY (plan_id) REFERENCES public.plan(plan_id) ON DELETE CASCADE
);

-- The signing secret for this key, encrypted (web::signing). Not hashed:
-- verifying an HMAC means computing it, which means holding the same secret
-- the caller holds — so it has to be recoverable. The key that opens it lives
-- in Secrets Manager, so reading this table is not enough.
--
-- NULL on keys made before request signing existed, which keep working as
-- bearer tokens. A key that HAS a secret may only be used signed: accepting it
-- as a bearer token would give away the very property signing adds.
ALTER TABLE public.api_key ADD COLUMN IF NOT EXISTS secret_sealed text;

-- Who made the key. A key acts for the whole workspace, so one made by a
-- teammate stops working when they leave it (checked at authentication, and
-- revoked by `store::remove_member`). NULL = made before this was recorded, or
-- by the operator endpoint, which answers only to the workspace itself.
ALTER TABLE public.api_key ADD COLUMN IF NOT EXISTS created_by bigint;
