-- Download API credentials. Only the SHA-256 of the token is stored; the token
-- itself is shown once, at creation. No foreign key to account: ownership is
-- enforced in application code, where every store function filters by it.
CREATE TABLE IF NOT EXISTS public.api_key (
	key_id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	account_id  bigint NOT NULL,
	-- NULL = every plan the account owns.
	plan_id     bigint,
	token_hash  char(64) NOT NULL,
	token_hint  varchar(16) NOT NULL DEFAULT '',
	label      varchar(120) NOT NULL DEFAULT '',
	-- CSV of IPs/CIDRs; '' = anywhere.
	allow_cidr  text NOT NULL DEFAULT '',
	expires_at  timestamptz,
	created_at  timestamptz NOT NULL DEFAULT now(),
	last_used_at timestamptz,
	last_used_ip varchar(64) NOT NULL DEFAULT '',
	uses       integer NOT NULL DEFAULT 0,
	revoked    boolean NOT NULL DEFAULT false,
	PRIMARY KEY (key_id),
	UNIQUE (token_hash),
	FOREIGN KEY (plan_id) REFERENCES public.plan(plan_id) ON DELETE CASCADE
);
