-- A stored row from a custom-artifact plan (Plan.kind = 'artifacts'): anything
-- collected off the web that isn't a people/company prospect — used cars, job
-- postings, rentals, grants, products. The columns are defined per-plan by
-- Plan.fields_schema_json; the values live in fields_json, so this one table
-- holds every artifact shape. Dedupe is the same (plan_id, source_key) mechanism
-- as prospect; meta_data keeps the full raw scraped row.
CREATE TABLE IF NOT EXISTS public.artifact (
	artifact_id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	plan_id       bigint NOT NULL,
	account_id    bigint NOT NULL,
	-- The dedupe identity (rendered from the schema's key-role field).
	source_key    text NOT NULL,
	-- A human label for the row (schema title-role field).
	title        text NOT NULL DEFAULT '',
	-- The source link (schema url-role field), for click-through.
	url          text NOT NULL DEFAULT '',
	-- The schema-defined columns and their values.
	fields_json   jsonb NOT NULL DEFAULT '{}'::jsonb,
	-- The full raw scraped row, so columns can be re-projected without re-scraping.
	meta_data     jsonb NOT NULL DEFAULT '{}'::jsonb,
	first_seen_utc timestamptz NOT NULL DEFAULT now(),
	last_seen_utc  timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (artifact_id),
	UNIQUE (plan_id, source_key),
	FOREIGN KEY (plan_id) REFERENCES public.plan(plan_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS artifact_account_seen_idx ON public.artifact (account_id, last_seen_utc DESC);
