-- A file collected by an assets plan (Plan.kind = 'assets'): the actual
-- documents found about a subject — filings, decks, spec sheets, images.
--
-- Only metadata lives here. The bytes go to the object store (objstore.rs)
-- under object_key, because runs execute in worker VMs whose filesystem the
-- app VM serving the file cannot read.
-- Dedupe is by content hash, so the same file found at two URLs is stored once.
CREATE TABLE IF NOT EXISTS public.asset (
	asset_id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	plan_id       bigint NOT NULL,
	account_id    bigint NOT NULL,
	execution_id        bigint,
	-- Dedupe identity: the sha256 of the file contents.
	source_key    text NOT NULL,
	sha256       text NOT NULL DEFAULT '',
	-- Where it came from, and what the agent called it.
	source_url    text NOT NULL DEFAULT '',
	title        text NOT NULL DEFAULT '',
	filename     text NOT NULL DEFAULT '',
	content_type  text NOT NULL DEFAULT '',
	size_bytes    bigint NOT NULL DEFAULT 0,
	-- The key the bytes live under in the object store.
	object_key    text NOT NULL DEFAULT '',
	-- The raw row the agent returned, for re-projection without re-fetching.
	meta_data     jsonb NOT NULL DEFAULT '{}'::jsonb,
	first_seen_utc timestamptz NOT NULL DEFAULT now(),
	last_seen_utc  timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (asset_id),
	UNIQUE (plan_id, source_key),
	FOREIGN KEY (plan_id) REFERENCES public.plan(plan_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS asset_account_seen_idx ON public.asset (account_id, last_seen_utc DESC);
