-- One prepaid-credit purchase. Stripe's payment_intent id is the uniqueness
-- key so a retried confirm cannot credit the wallet twice. Mock purchases in
-- local development use a `mock_…` handle so the same path is exercised.
CREATE TABLE IF NOT EXISTS public.credit_purchase (
	purchase_id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	account_id           bigint NOT NULL,
	usd_micros           bigint NOT NULL,
	payment_ref          varchar(120) NOT NULL,
	status               varchar(24) NOT NULL DEFAULT 'succeeded',
	created_at           timestamptz NOT NULL DEFAULT now(),
	-- Cumulative amount reversed by Stripe refunds/disputes. Webhook retries
	-- set a target and apply only the positive delta.
	reversed_usd_micros  bigint NOT NULL DEFAULT 0,
	PRIMARY KEY (purchase_id),
	CONSTRAINT credit_purchase_amount_positive CHECK (usd_micros > 0),
	CONSTRAINT credit_purchase_reversed_valid CHECK (reversed_usd_micros >= 0 AND reversed_usd_micros <= usd_micros)
);
CREATE UNIQUE INDEX IF NOT EXISTS credit_purchase_payment_ref_idx
	ON public.credit_purchase (payment_ref);
CREATE INDEX IF NOT EXISTS credit_purchase_account_idx
	ON public.credit_purchase (account_id, created_at DESC);

-- Credit an operator adds by hand (2026-09-28) lands here too, so the wallet
-- has one history: 'purchase' is paid through Stripe (or the local mock),
-- 'grant' is free credit from the admin — never revenue. A grant's
-- payment_ref is 'grant_…', its note is what the operator wrote, and
-- granted_by is the operator's address.
ALTER TABLE public.credit_purchase ADD COLUMN IF NOT EXISTS kind varchar(12) NOT NULL DEFAULT 'purchase';
ALTER TABLE public.credit_purchase ADD COLUMN IF NOT EXISTS note text NOT NULL DEFAULT '';
ALTER TABLE public.credit_purchase ADD COLUMN IF NOT EXISTS granted_by varchar(320) NOT NULL DEFAULT '';
