-- One execution of a plan. The server inserts the row, spawns
-- `huntwell run --execution-id`, and the child reports back through status and
-- execution_log. Status: queued | running | succeeded | failed | cancelled.
CREATE TABLE IF NOT EXISTS public.execution (
	execution_id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	plan_id     bigint NOT NULL,
	account_id  bigint NOT NULL,
	status     varchar(12) NOT NULL DEFAULT 'queued',
	trigger    varchar(12) NOT NULL DEFAULT 'manual',
	started_at  timestamptz NOT NULL DEFAULT now(),
	finished_at timestamptz,
	exit_code   integer,
	args_json   jsonb NOT NULL DEFAULT '{}'::jsonb,
	pid        integer,
	cdp_port    integer,
	-- Set by the child at the end: prospects stored this execution.
	new_prospects integer NOT NULL DEFAULT 0,
	PRIMARY KEY (execution_id),
	FOREIGN KEY (plan_id) REFERENCES public.plan(plan_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS execution_account_started_idx ON public.execution (account_id, started_at DESC);
CREATE INDEX IF NOT EXISTS execution_active_idx ON public.execution (plan_id) WHERE status IN ('queued','running');

-- Token usage, accumulated live as each agent call in the execution reports its
-- `usage` (see agent.rs). This is the billing meter: summed per account per
-- period against account_usage to enforce the usage cap.
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS input_tokens      bigint NOT NULL DEFAULT 0;
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS output_tokens     bigint NOT NULL DEFAULT 0;
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS cache_read_tokens  bigint NOT NULL DEFAULT 0;
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS cache_write_tokens bigint NOT NULL DEFAULT 0;
-- Our cost of goods for this execution, in micro-dollars (1e-6 USD): Cursor's
-- `total_cost_usd`, populated once Cursor billing is usage-based. Kept beside
-- the tokens so per-account margin (billed minus this) is a simple sum.
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS cost_usd_micros bigint NOT NULL DEFAULT 0;

-- Pool-dispatch placement (RUN_DISPATCH=pool): the admin control plane
-- assigns a queued execution to a warm worker pod on a host; the pod's supervisor
-- claims it and heartbeats while it executes. host_id deliberately has NO
-- foreign key — execution history must survive host deletion (admin refuses to
-- delete a host with non-terminal executions, in code).
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS host_id          bigint;
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS pod_name         varchar(80);
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS claimed_at       timestamptz;
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS heartbeat_at     timestamptz;
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS cancel_requested boolean NOT NULL DEFAULT false;
-- The pod supervisor's claim query: assigned to me, still unclaimed.
CREATE INDEX IF NOT EXISTS execution_pool_claim_idx ON public.execution (host_id, pod_name)
	WHERE status = 'queued' AND claimed_at IS NULL;

-- The remote browser session this execution drove, so the owner can watch it
-- while it runs. Only the id: the viewing URL is a bearer capability and is
-- fetched fresh, per request, for whoever proves they own the execution.
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS browser_session_id text NOT NULL DEFAULT '';
