-- One execution of a plan. The website inserts the row, a worker slot claims
-- it, and the run reports back through status and execution_log. Status:
-- queued | running | succeeded | failed | cancelled.
CREATE TABLE IF NOT EXISTS public.execution (
	execution_id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	plan_id            bigint NOT NULL,
	account_id         bigint NOT NULL,
	status             varchar(12) NOT NULL DEFAULT 'queued',
	trigger            varchar(12) NOT NULL DEFAULT 'manual',
	started_at         timestamptz NOT NULL DEFAULT now(),
	finished_at        timestamptz,
	exit_code          integer,
	args_json          jsonb NOT NULL DEFAULT '{}'::jsonb,
	pid                integer,
	cdp_port           integer,
	-- Set by the run at the end: prospects stored this execution.
	new_prospects      integer NOT NULL DEFAULT 0,
	-- Token usage, accumulated live as each agent call reports its `usage`
	-- (agent.rs). This is the billing meter: booked against account_usage as
	-- it happens.
	input_tokens       bigint NOT NULL DEFAULT 0,
	output_tokens      bigint NOT NULL DEFAULT 0,
	cache_read_tokens  bigint NOT NULL DEFAULT 0,
	cache_write_tokens bigint NOT NULL DEFAULT 0,
	-- Our cost of goods for this execution, in micro-dollars: Cursor's
	-- `total_cost_usd`, populated when Cursor billing is usage-based. Beside
	-- the tokens so per-account margin (billed minus this) is a simple sum.
	cost_usd_micros    bigint NOT NULL DEFAULT 0,
	-- Placement (RUN_DISPATCH=pool): the admin assigns a queued execution to a
	-- worker slot — `huntwell-worker@N` in a worker VM — which claims it and
	-- heartbeats while it executes. host_id deliberately has NO foreign key:
	-- history must survive host deletion (the admin refuses to delete a host
	-- with non-terminal executions, in code).
	host_id            bigint,
	slot_name          varchar(80),
	claimed_at         timestamptz,
	heartbeat_at       timestamptz,
	cancel_requested   boolean NOT NULL DEFAULT false,
	-- The remote browser session this execution drove, so the owner can watch
	-- it while it runs. Only the id: the viewing URL is a bearer capability,
	-- fetched fresh per request for whoever proves they own the execution.
	browser_session_id text NOT NULL DEFAULT '',
	PRIMARY KEY (execution_id),
	FOREIGN KEY (plan_id) REFERENCES public.plan(plan_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS execution_account_started_idx ON public.execution (account_id, started_at DESC);
CREATE INDEX IF NOT EXISTS execution_active_idx ON public.execution (plan_id) WHERE status IN ('queued','running');
-- One prepaid wallet cannot safely fund two in-flight agent processes: each
-- can have a token slice the provider has not reported yet. Kept in Postgres
-- as well as the runner so the website and scheduler cannot race.
CREATE UNIQUE INDEX IF NOT EXISTS execution_one_active_per_account_idx
	ON public.execution (account_id) WHERE status IN ('queued','running');
-- A slot's claim query: assigned to me, still unclaimed.
CREATE INDEX IF NOT EXISTS execution_pool_claim_idx ON public.execution (host_id, slot_name)
	WHERE status = 'queued' AND claimed_at IS NULL;
-- The model the scrape stage ran on ('' = Cursor's auto). Scrape is where the
-- tokens go, so it is the rate the admin's cost estimate uses when Cursor
-- reported no cost of its own (cost_usd_micros = 0).
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS model_scrape varchar(160) NOT NULL DEFAULT '';
-- Why a run did no work, when it did none: 'unchanged' = the pages this plan
-- watches showed nothing new, so no agent was started (thrift::watch). Also how
-- consecutive skips are counted, so a plan is never skipped indefinitely.
ALTER TABLE public.execution ADD COLUMN IF NOT EXISTS skipped_reason varchar(40) NOT NULL DEFAULT '';
