-- A k3d/k3s compute host managed by the admin control plane. Each enabled
-- host runs a warm StatefulSet pool of `worker-pool` pods; the admin's
-- placement loop assigns queued runs to (host_id, pod_name). Operator-scoped —
-- no account_id, by design: hosts belong to the operator, not to a tenant
-- (documented exception to the every-table-carries-account_id rule).
CREATE TABLE IF NOT EXISTS public.host (
	host_id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name           varchar(120) NOT NULL,
	-- Full kubeconfig YAML, pasted at registration. Materialized to a 0600
	-- file by the admin at startup/update; never returned to the browser.
	kubeconfig_yaml text NOT NULL DEFAULT '',
	kube_context    varchar(200),
	enabled        boolean NOT NULL DEFAULT true,
	-- Warm pool size: the StatefulSet replica count (pods hw-pool-0..N-1).
	pool_size       integer NOT NULL DEFAULT 2,
	-- Kubernetes quantity strings, editable in the admin UI and applied on
	-- the next reconcile — resources live in data, not code.
	cpu_request     varchar(20) NOT NULL DEFAULT '250m',
	cpu_limit       varchar(20) NOT NULL DEFAULT '1',
	mem_request     varchar(20) NOT NULL DEFAULT '512Mi',
	mem_limit       varchar(20) NOT NULL DEFAULT '1Gi',
	image          varchar(200) NOT NULL DEFAULT 'huntwell-worker:dev',
	notes          text NOT NULL DEFAULT '',
	-- Health from the last kubectl reconcile. A transport failure is recorded
	-- here and the host is skipped by placement — it is never conflated with
	-- "zero pods".
	last_error      text,
	last_seen_at     timestamptz,
	created_at      timestamptz NOT NULL DEFAULT now(),
	updated_at      timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (host_id),
	UNIQUE (name)
);

-- Whether the admin deploys the application services here (website, planning,
-- scheduling, notification and the bus) as well as the worker pool. Off means
-- a pure compute host: it executes runs and serves nothing anyone signs in to.
-- On means this cluster is the whole installation, which is the one-server
-- shape — there is no separate web tier to install.
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS runs_services boolean NOT NULL DEFAULT false;

-- Replicas of the one service anything connects to. The other three are queue
-- readers: one is enough, and a second scheduling copy is a warm standby
-- (they contend for an advisory lock) rather than duplicate work.
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS web_replicas integer NOT NULL DEFAULT 1;
