-- A bare-metal server the admin control plane places VMs on (vm.sql), or the
-- process-backed local host ./dev.sh registers. Operator-scoped — no
-- account_id, by design: hosts belong to the operator, not to a tenant
-- (documented exception to the every-table-carries-account_id rule).
CREATE TABLE IF NOT EXISTS public.host (
	host_id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	-- Also the Incus remote the admin's certificate is registered under.
	name           varchar(120) NOT NULL,
	enabled        boolean NOT NULL DEFAULT true,
	-- Worker children of the admin, on the local host only (HUNTWELL_LOCAL_POOL).
	-- An Incus host's capacity is the slots of its worker VMs.
	pool_size       integer NOT NULL DEFAULT 2,
	notes          text NOT NULL DEFAULT '',
	-- Health from the last check. A failure is recorded here and the host is
	-- skipped by placement — it is never conflated with "zero slots".
	last_error      text,
	last_seen_at     timestamptz,
	created_at      timestamptz NOT NULL DEFAULT now(),
	updated_at      timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (host_id),
	UNIQUE (name)
);

-- ── Incus ────────────────────────────────────────────────────────────────────
--
-- The admin reaches a host through the Incus API with its own client certificate,
-- trusted once with a token from `sys incus token`; `name` is the Incus remote
-- that certificate is registered under. No credential is stored here.
--
-- A host carries VMs (vm.sql): at most one app VM for the whole installation,
-- and worker VMs of N plan slots each. 2–3 VMs per server is the intended
-- shape — the point being that a compromise stops at one VM's credentials.

-- Incus API endpoint, e.g. https://10.0.0.1:8443.
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS endpoint varchar(255) NOT NULL DEFAULT '';

-- Active   = new VMs may be placed here
-- Draining = keeps its VMs, takes no new ones (an operator's decision)
-- Offline  = unreachable at the last health check; placement skips it
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS status varchar(24) NOT NULL DEFAULT 'Active';

-- The golden image VMs start from, built on the host by `sys incus image`.
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS base_image varchar(120) NOT NULL DEFAULT 'huntwell';

-- Placement: lower priority goes first among equally loaded hosts, and a host
-- never takes more than max_vms. 0 = no limit.
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS priority integer NOT NULL DEFAULT 100;
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS max_vms integer NOT NULL DEFAULT 3;

-- The shape a new VM on this host gets unless the provision says otherwise.
-- Sized for ~10 concurrent plans: each runs an agent, and planning alone asks
-- for 3 GB.
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS vm_cpu integer NOT NULL DEFAULT 8;
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS vm_memory varchar(32) NOT NULL DEFAULT '16GiB';
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS vm_disk varchar(32) NOT NULL DEFAULT '60GiB';
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS vm_slots integer NOT NULL DEFAULT 10;

-- The edge. Only meaningful on the host carrying the app VM: a Caddy container
-- there routes ingress_domain to it.
--   https      = Caddy on the host's 80/443, getting its own certificates
--   http       = plain, for a private network or a laptop
--   cloudflare = reached through a Cloudflare Tunnel; no public IP needed
-- edge_port 0 = the scheme's default.
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS ingress_domain varchar(160) NOT NULL DEFAULT '';
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS edge_scheme varchar(16) NOT NULL DEFAULT 'https';
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS edge_port integer NOT NULL DEFAULT 0;

-- The last health check, from the Incus API. arch decides which build a VM on
-- this host is given: an x86_64 host runs bin/ubuntu, aarch64 bin/ubuntu-arm64.
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS arch varchar(16) NOT NULL DEFAULT '';
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS incus_version varchar(60) NOT NULL DEFAULT '';
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS cpu_total integer NOT NULL DEFAULT 0;
ALTER TABLE public.host ADD COLUMN IF NOT EXISTS memory_total_mb bigint NOT NULL DEFAULT 0;
