-- An outstanding invitation to a workspace.
--
-- There is no mail sender in this system, so the invite is a link the inviter
-- copies and sends however they like. The token is what the link carries and
-- the only secret involved: it is single-use, expires, and is bound to the
-- email it was addressed to so a forwarded link cannot be redeemed by someone
-- else.
CREATE TABLE IF NOT EXISTS public.invite (
	invite_id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	workspace_id  bigint NOT NULL,
	-- Lowercased, like account.email, so the match is case-insensitive.
	email        varchar(320) NOT NULL,
	role         varchar(12) NOT NULL DEFAULT 'member',
	-- Random, URL-safe, and the whole authorisation: never guessable.
	token        varchar(64) NOT NULL,
	invited_by_id  bigint NOT NULL,
	created_at    timestamptz NOT NULL DEFAULT now(),
	expires_at    timestamptz NOT NULL DEFAULT now() + interval '14 days',
	accepted_at   timestamptz,
	accepted_by_id bigint,
	PRIMARY KEY (invite_id),
	UNIQUE (token)
);
CREATE INDEX IF NOT EXISTS invite_workspace_idx ON public.invite (workspace_id) WHERE accepted_at IS NULL;
