-- Outbound mail, queued rather than sent inline.
--
-- Sending used to happen on the request path: an invite blocked the HTTP
-- response on a call to the mail provider, and a provider hiccup turned into a
-- slow signup or a silently dropped message with no record and no retry. A row
-- here is the record, and the notification service is the only thing that talks
-- to the provider.
--
-- account_id is provenance, not a fence: the notification service claims across
-- every tenant the way the run pool and the planning service do. It is nullable
-- because the first message an address ever gets — confirm your email — may
-- precede the account it belongs to.
CREATE TABLE IF NOT EXISTS public.mail_outbox (
	mail_id        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	account_id     bigint,
	to_address     text        NOT NULL,
	subject       text        NOT NULL,
	html          text        NOT NULL,
	text          text        NOT NULL,
	-- What this message is, for support questions and for rate decisions later:
	-- 'verification' | 'welcome' | 'invite' | 'new_records'.
	kind          varchar(24) NOT NULL DEFAULT '',
	attempts      integer     NOT NULL DEFAULT 0,
	-- When it may next be tried. Set ahead on failure, which is the backoff.
	next_attempt_at timestamptz NOT NULL DEFAULT now(),
	-- Set once, when the provider accepted it. NULL means still owed.
	sent_at        timestamptz,
	last_error     text        NOT NULL DEFAULT '',
	created_at     timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (mail_id)
);

-- The claim probe: everything owed and due, oldest first. Partial, because sent
-- mail is the overwhelming majority of the table and is never queried this way.
CREATE INDEX IF NOT EXISTS mail_outbox_due_idx
    ON public.mail_outbox (next_attempt_at)
    WHERE sent_at IS NULL;
