-- A cold outreach email drafted for one recipient. The current text is here;
-- every version it went through is in `outreach_version`. Nothing is sent:
-- the person copies it into their own mail.
CREATE TABLE IF NOT EXISTS public.outreach (
	outreach_id        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	-- The workspace it belongs to.
	account_id         bigint NOT NULL,
	-- Who drafted it; their footer is the one appended.
	created_by         bigint NOT NULL,
	-- The prospect it was drafted from, if any. A draft outlives the prospect.
	prospect_id        bigint,
	recipient_name     varchar(200) NOT NULL DEFAULT '',
	recipient_email    varchar(320) NOT NULL DEFAULT '',
	recipient_title    varchar(200) NOT NULL DEFAULT '',
	recipient_company  varchar(200) NOT NULL DEFAULT '',
	-- Anything else the person typed about a hand-entered recipient.
	recipient_notes    text NOT NULL DEFAULT '',
	subject            varchar(300) NOT NULL DEFAULT '',
	-- The body the model wrote (or the person edited), without the footer.
	body               text NOT NULL DEFAULT '',
	-- The footer as it was when drafted, appended verbatim on copy.
	footer             text NOT NULL DEFAULT '',
	version            integer NOT NULL DEFAULT 1,
	created_at         timestamptz NOT NULL DEFAULT now(),
	updated_at         timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (outreach_id),
	FOREIGN KEY (account_id) REFERENCES public.account(account_id) ON DELETE CASCADE,
	FOREIGN KEY (prospect_id) REFERENCES public.prospect(prospect_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS outreach_account_idx ON public.outreach (account_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS outreach_prospect_idx ON public.outreach (prospect_id) WHERE prospect_id IS NOT NULL;
