-- Every version of an outreach draft: the first draft, each revision from
-- feedback, and each hand edit. Kept so a person can go back to one they liked.
CREATE TABLE IF NOT EXISTS public.outreach_version (
	outreach_version_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	outreach_id    bigint NOT NULL,
	-- Repeated from the parent so every read can filter on the workspace.
	account_id     bigint NOT NULL,
	version        integer NOT NULL,
	subject        varchar(300) NOT NULL DEFAULT '',
	body           text NOT NULL DEFAULT '',
	-- draft | revise | edit | restore
	source         varchar(12) NOT NULL DEFAULT 'draft',
	-- The feedback a revision was asked for; '' otherwise.
	feedback       text NOT NULL DEFAULT '',
	model          varchar(160) NOT NULL DEFAULT '',
	input_tokens   integer NOT NULL DEFAULT 0,
	output_tokens  integer NOT NULL DEFAULT 0,
	created_by     bigint,
	created_at     timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (outreach_version_id),
	UNIQUE (outreach_id, version),
	FOREIGN KEY (outreach_id) REFERENCES public.outreach(outreach_id) ON DELETE CASCADE
);
