-- Saved outreach profiles (2026-09-27): a named design — who the emails are
-- for and the angle, what to offer, and rules on top of the workspace's
-- (outreach_profile) — that is not tied to any plan. Picked when drafting,
-- or by a plan as its outreach instead of writing its own.
CREATE TABLE IF NOT EXISTS public.outreach_design (
	design_id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	account_id  bigint NOT NULL,
	name        varchar(120) NOT NULL,
	brief       text NOT NULL DEFAULT '',
	-- Replaces the workspace's product description when set.
	product     text NOT NULL DEFAULT '',
	-- Added to the workspace's rules; these win where they differ.
	rules       text NOT NULL DEFAULT '',
	created_by  bigint,
	created_at  timestamptz NOT NULL DEFAULT now(),
	updated_at  timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (design_id),
	FOREIGN KEY (account_id) REFERENCES public.account(account_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS outreach_design_name_idx ON public.outreach_design (account_id, lower(name));

-- A plan may use a saved profile as its outreach (when outreach_custom is
-- off). Here rather than in plan.sql: the table has to exist first.
ALTER TABLE public.plan ADD COLUMN IF NOT EXISTS outreach_design_id bigint REFERENCES public.outreach_design (design_id) ON DELETE SET NULL;
