-- A prospecting plan: the original huntwell's SourceConfig, owned by an
-- account. Prompts, mapping templates, seed vars, behaviour flags and the
-- schedule all live here; a run reads this row and nothing else.
--
-- (account_id, source) is unique — the plan name is what a user types and what
-- the CSV's Source column shows — but every child table keys on plan_id so a
-- rename is one UPDATE here.
CREATE TABLE IF NOT EXISTS public.plan (
	plan_id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	account_id            bigint NOT NULL,
	source               varchar(120) NOT NULL,
	-- 'business' (a person in a company context) or 'individual' (a private
	-- person). Selects which prompt family the wizard drafts and which column
	-- is replayed as the exclusion list.
	plan_type             varchar(16) NOT NULL DEFAULT 'business',
	scrape_prompt         text NOT NULL DEFAULT '',
	enrich_prompt         text NOT NULL DEFAULT '',
	planner_prompt        text NOT NULL DEFAULT '',
	-- Mapping templates: {{.field}} over the scraped row plus seed vars.
	source_key_tmpl        text NOT NULL DEFAULT '',
	name_tmpl             text NOT NULL DEFAULT '',
	title_tmpl            text NOT NULL DEFAULT '',
	company_tmpl          text NOT NULL DEFAULT '',
	industry_tmpl         text NOT NULL DEFAULT '',
	email_tmpl            text NOT NULL DEFAULT '',
	email_status_tmpl      text NOT NULL DEFAULT '',
	phone_tmpl            text NOT NULL DEFAULT '',
	website_tmpl          text NOT NULL DEFAULT '',
	linkedin_tmpl         text NOT NULL DEFAULT '',
	location_tmpl         text NOT NULL DEFAULT '',
	notes_tmpl            text NOT NULL DEFAULT '',
	linkedin_message_tmpl  text NOT NULL DEFAULT '',
	cold_email_subject_tmpl text NOT NULL DEFAULT '',
	cold_email_body_tmpl    text NOT NULL DEFAULT '',
	estimated_value_tmpl   text NOT NULL DEFAULT '',
	min_value             bigint NOT NULL DEFAULT 0,
	learn                boolean NOT NULL DEFAULT false,
	iterations           integer NOT NULL DEFAULT 1,
	max_no_progress        integer NOT NULL DEFAULT 2,
	-- The exclusion list a scrape prompt replays as {{.known_companies_csv}}. 60
	-- names: the agent has prospect_known(), which answers the same question
	-- for a whole results page in one call against the full record.
	known_limit           integer NOT NULL DEFAULT 60,
	target_prospects      integer NOT NULL DEFAULT 0,
	free_agent            boolean NOT NULL DEFAULT false,
	favorite             boolean NOT NULL DEFAULT false,
	-- Cursor `agent --model` id; '' lets Cursor pick.
	model                varchar(160) NOT NULL DEFAULT '',
	seed_vars_json         text NOT NULL DEFAULT '{}',
	-- Hosts the browser may touch, comma separated; '' = unrestricted.
	allow_hosts           text NOT NULL DEFAULT '',
	-- Recurring schedule: local wall-clock HH:MM in the account's timezone,
	-- and a CSV of weekdays (0=Sunday) or '' for every day.
	schedule_enabled      boolean NOT NULL DEFAULT false,
	schedule_time         varchar(5) NOT NULL DEFAULT '',
	schedule_days         varchar(20) NOT NULL DEFAULT '',
	-- Derived from the three above; server-owned, a client can never set it.
	next_run_at            timestamptz,
	last_scheduled_at      timestamptz,
	created_at            timestamptz NOT NULL DEFAULT now(),
	updated_at            timestamptz NOT NULL DEFAULT now(),
	-- What a plan collects. 'prospects' (default) uses the fixed people/company
	-- columns and the *Tmpl mapping; 'artifacts' collects arbitrary rows whose
	-- columns are defined by fields_schema_json (a JSON array of {key,label,
	-- type,role}); 'report' writes one narrative document about subject (the
	-- report table); 'assets' collects the actual files found about it.
	kind                  varchar(16) NOT NULL DEFAULT 'prospects',
	fields_schema_json    text NOT NULL DEFAULT '',
	-- For 'report' and 'assets': the one company, person or topic the run is
	-- about. It is also the dedupe key, so re-running refreshes in place.
	subject               varchar(300) NOT NULL DEFAULT '',
	-- The plan in the user's own words: the brief they typed, kept as the one
	-- human-readable thing the UI shows about a plan. Everything that makes
	-- the plan work — the prompts, the mapping, the dedupe key — is machinery
	-- the drafting agent writes and the app never puts on screen.
	description           varchar(600) NOT NULL DEFAULT '',
	-- How hard a run should try, as one choice instead of two machine knobs.
	-- 'quick' | 'normal' | 'thorough' | 'exhaustive'. The server derives
	-- iterations, max_no_progress and learn from it (web::api::apply_effort).
	effort                varchar(12) NOT NULL DEFAULT 'normal',
	-- Where the plan is in being built: 'queued' for the planning service,
	-- 'drafting' while the agent authors its prompts (the row exists at once
	-- so the plan shows up, spinning), 'ready' once written, 'failed' if the
	-- agent could not — a failed plan stays visible so it can be retried.
	draft_status          varchar(12) NOT NULL DEFAULT 'ready',
	-- Websites this plan should search first, comma-separated hosts. A
	-- preference, not a fence: allow_hosts is the containment allowlist.
	sites                 text NOT NULL DEFAULT '',
	-- Email the account when a run stores rows it had not seen before.
	alert_email           boolean NOT NULL DEFAULT false,
	-- Per-stage Cursor model ids the owner picked. Empty means "not chosen
	-- here": the run falls back to the all-stages `model`, then the install
	-- default, then Cursor's own pick. Search, research and find-files share
	-- scrape; enrichment and the next-search planner are their own jobs.
	model_scrape          varchar(160) NOT NULL DEFAULT '',
	model_enrich          varchar(160) NOT NULL DEFAULT '',
	model_planner         varchar(160) NOT NULL DEFAULT '',
	-- Drafting is a queue: the website marks a plan 'queued' and the planning
	-- service claims it with an atomic 'queued' -> 'drafting' UPDATE. This is
	-- the brief as the website received it, parked for the planning service;
	-- NOT re-derivable from the row (a plan of kind 'auto' has not been
	-- classified yet). Empty means "rebuild the request from this row".
	draft_request_json    text NOT NULL DEFAULT '',
	PRIMARY KEY (plan_id),
	UNIQUE (account_id, source)
);
CREATE INDEX IF NOT EXISTS plan_schedule_idx ON public.plan (next_run_at) WHERE schedule_enabled;
-- Claim probe: the planning service asks "is anything queued?" every couple of
-- seconds and the answer is almost always no. Partial, so it stays small.
CREATE INDEX IF NOT EXISTS plan_draft_queue_idx ON public.plan (plan_id)
    WHERE draft_status = 'queued';
