-- A stored lead. (plan_id, source_key) is the whole dedupe mechanism: source_key
-- is the rendered source_key_tmpl (a company domain on business plans, a
-- name-city slug on individual plans). meta_data keeps the full raw row so the
-- display columns can be re-projected without re-scraping.
CREATE TABLE IF NOT EXISTS public.prospect (
	prospect_id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	plan_id           bigint NOT NULL,
	account_id        bigint NOT NULL,
	name             text NOT NULL DEFAULT '',
	title            text NOT NULL DEFAULT '',
	company          text NOT NULL DEFAULT '',
	industry         text NOT NULL DEFAULT '',
	email            text NOT NULL DEFAULT '',
	email_status      text NOT NULL DEFAULT '',
	phone            text NOT NULL DEFAULT '',
	website          text NOT NULL DEFAULT '',
	linkedin         text NOT NULL DEFAULT '',
	location         text NOT NULL DEFAULT '',
	notes            text NOT NULL DEFAULT '',
	linkedin_message  text NOT NULL DEFAULT '',
	cold_email_subject text NOT NULL DEFAULT '',
	cold_email_body    text NOT NULL DEFAULT '',
	estimated_value   bigint,
	meta_data         jsonb NOT NULL DEFAULT '{}'::jsonb,
	source_key        text NOT NULL,
	first_seen_utc     timestamptz NOT NULL DEFAULT now(),
	last_seen_utc      timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (prospect_id),
	UNIQUE (plan_id, source_key),
	FOREIGN KEY (plan_id) REFERENCES public.plan(plan_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS prospect_account_seen_idx ON public.prospect (account_id, last_seen_utc DESC);
