-- One synthesized narrative document from a report plan (Plan.kind =
-- 'report'): everything the agent found about a subject, written as Markdown
-- with a list of the sources behind it. Unlike Prospect/Artifact this is one
-- row per subject, not many rows per run — re-running the plan refreshes the
-- document in place through the same (plan_id, source_key) dedupe.
--
-- The Markdown is rendered to HTML for reading and printing (Save-as-PDF is
-- the browser's job), so nothing binary is stored here.
CREATE TABLE IF NOT EXISTS public.report (
	report_id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	plan_id       bigint NOT NULL,
	account_id    bigint NOT NULL,
	-- The run that last wrote this document, for traceability.
	execution_id        bigint,
	-- Dedupe identity: a slug of the subject.
	source_key    text NOT NULL,
	-- What the report is about, and the document's own headline.
	subject      text NOT NULL DEFAULT '',
	title        text NOT NULL DEFAULT '',
	-- The report body. Markdown, rendered server-side with raw HTML escaped.
	markdown     text NOT NULL DEFAULT '',
	-- JSON array of {title,url} the report was built from.
	sources_json  jsonb NOT NULL DEFAULT '[]'::jsonb,
	word_count    integer NOT NULL DEFAULT 0,
	first_seen_utc timestamptz NOT NULL DEFAULT now(),
	last_seen_utc  timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (report_id),
	UNIQUE (plan_id, source_key),
	FOREIGN KEY (plan_id) REFERENCES public.plan(plan_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS report_account_seen_idx ON public.report (account_id, last_seen_utc DESC);
