-- The control plane's routing audit trail: one row per placement decision or
-- lifecycle event, so an operator can see exactly where every run went and
-- why it moved. Append-only; operator-scoped (no account_id — the run row
-- carries the tenant). Events: routed | requeued | reaped.
CREATE TABLE IF NOT EXISTS public.route_log (
	route_log_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	execution_id      bigint NOT NULL,
	event      varchar(16) NOT NULL,
	-- Where it went (NULL for events that detach a run from a pod).
	host_id     bigint,
	pod_name    varchar(80),
	-- Free text: the strategy used, or why the run moved.
	detail     varchar(200) NOT NULL DEFAULT '',
	created_at  timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (route_log_id)
);
CREATE INDEX IF NOT EXISTS route_log_created_idx ON public.route_log (created_at DESC);
