-- Slack posts owed for a run's new results, queued rather than sent inline.
--
-- The run that found the rows usually lives on a worker VM, which by design
-- holds neither the key that opens a plan's sealed webhook nor the public URL
-- the post links to. So the run writes this row and the notification service
-- (app VM) renders and delivers it, with the same retry-and-backoff as mail.
--
-- The rows posted are the plan's rows first seen in [since, created_at]: the
-- run's own finds, re-read at send time, so a retry renders the same post and
-- a later run's rows never leak into it.
CREATE TABLE IF NOT EXISTS public.slack_outbox (
	slack_id        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	account_id      bigint      NOT NULL,
	plan_id         bigint      NOT NULL REFERENCES public.plan (plan_id) ON DELETE CASCADE,
	execution_id    bigint,
	since           timestamptz NOT NULL,
	-- A long post goes out as several messages. A retry after a partial send
	-- resumes after the last one Slack accepted instead of repeating them.
	parts_sent      integer     NOT NULL DEFAULT 0,
	attempts        integer     NOT NULL DEFAULT 0,
	next_attempt_at timestamptz NOT NULL DEFAULT now(),
	sent_at         timestamptz,
	last_error      text        NOT NULL DEFAULT '',
	created_at      timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (slack_id)
);

CREATE INDEX IF NOT EXISTS slack_outbox_due_idx
    ON public.slack_outbox (next_attempt_at)
    WHERE sent_at IS NULL;
