-- A virtual machine on an Incus host (host.sql). The whole application runs in
-- these: one app VM serves the product, and worker VMs execute plans.
--
--   app     website · planning · scheduling · notification · nats, under
--           systemd, behind the host's edge. At most one per installation.
--   worker  N `huntwell-worker@` slots. Each slot is a worker-pool process that
--           claims one run at a time, assigned to it as (host_id, slot name).
--
-- Operator-scoped, no account_id: VMs belong to the installation, not a tenant
-- (the same documented exception as host).
CREATE TABLE IF NOT EXISTS public.vm (
	vm_id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	-- No ON DELETE: a host with VMs on it refuses to be deleted, because the
	-- VMs are real machines and a vanished row would orphan them silently.
	host_id    bigint NOT NULL,
	-- The Incus instance name. Unique across the installation so a slot name
	-- (`<name>-<n>`) identifies one process wherever it runs.
	name       varchar(63) NOT NULL,
	role       varchar(16) NOT NULL,
	-- Concurrent plans on a worker. Ignored on the app VM.
	slots      integer NOT NULL DEFAULT 10,
	cpu        integer NOT NULL DEFAULT 8,
	memory     varchar(32) NOT NULL DEFAULT '16GiB',
	disk       varchar(32) NOT NULL DEFAULT '60GiB',
	-- Provisioning  being created or re-created
	-- Running       its units are up
	-- Stopped       stopped by an operator; its slots take no runs
	-- Failed        provisioning or a deploy did not finish — last_error says why
	status     varchar(24) NOT NULL DEFAULT 'Provisioning',
	-- sha256[:12] of the build running inside, which names the exact bytes —
	-- a hand-copied build folder cannot promise that of any other label.
	version    varchar(64) NOT NULL DEFAULT '',
	-- The VM's address on the host bridge at the last check. Asked of Incus
	-- again before routing to it; this copy is for the console.
	address    varchar(64) NOT NULL DEFAULT '',
	last_error text NOT NULL DEFAULT '',
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (vm_id),
	UNIQUE (name),
	FOREIGN KEY (host_id) REFERENCES public.host(host_id),
	CONSTRAINT vm_role_ck CHECK (role IN ('app', 'worker')),
	CONSTRAINT vm_status_ck CHECK (status IN ('Provisioning', 'Running', 'Stopped', 'Failed'))
);
CREATE INDEX IF NOT EXISTS vm_host_idx ON public.vm (host_id);

-- One app VM. Two would each run the scheduler and each think it owned the
-- edge's route, and nothing about the product is built to be two copies yet.
CREATE UNIQUE INDEX IF NOT EXISTS vm_one_app_idx ON public.vm (role) WHERE role = 'app';
