-- Who may create an account while sign-up is invite-only.
--
-- One row per email address, whichever way it arrived: a person asking to be
-- let in from the sign-up page ('waiting'), or an operator inviting them from
-- the admin ('invited' straight away). Approving a waiting row is the same act
-- as inviting — it mints a token and emails the link — so the admin works from
-- one list rather than two.
--
-- Not a tenant table: it exists before there is an account to belong to, and
-- only the admin reads it. `account_id` records who the row became.
CREATE TABLE IF NOT EXISTS public.waitlist (
	waitlist_id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	-- Lowercased, like account.email, so one person is one row.
	email         varchar(320) NOT NULL,
	name          varchar(80) NOT NULL DEFAULT '',
	-- What they said they want Huntwell for. Theirs, unvetted, shown to an
	-- operator deciding whether to let them in and nowhere else.
	note          varchar(600) NOT NULL DEFAULT '',
	-- 'waiting' | 'invited' | 'joined' | 'declined'
	status        varchar(12) NOT NULL DEFAULT 'waiting',
	requested_at  timestamptz,
	requested_ip  varchar(64) NOT NULL DEFAULT '',
	invited_at    timestamptz,
	-- The operator's email, for "who let this person in".
	invited_by    varchar(320) NOT NULL DEFAULT '',
	-- SHA-256 of the token the invite link carries. The token itself is only
	-- ever in the email: a database read gives no one a way in.
	invite_token_hash char(64),
	invite_expires_at timestamptz,
	joined_at     timestamptz,
	account_id    bigint,
	declined_at   timestamptz,
	created_at    timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (waitlist_id),
	UNIQUE (email)
);
CREATE UNIQUE INDEX IF NOT EXISTS waitlist_token_idx ON public.waitlist (invite_token_hash) WHERE invite_token_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS waitlist_status_idx ON public.waitlist (status, created_at DESC);
