apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - rbac.yaml
  - postgres.yaml
  - nats.yaml
  - migrate.yaml
  - services.yaml
  - ingress.yaml
